Repository Rio-Song-kr/TheSinkhole, pull requests merged in 2025-06, with the labels that each got.

#24 [Feat] 플레이어 빗면 움직임 구현
  Assets/GIL/Input Actions/PlayerInput.cs
  Assets/GIL/Input Actions/PlayerInput.inputactions
  Assets/GIL/Scenes/[Test] PlayerMovementScene.unity
  Assets/GIL/Scripts/Movement/PlayerInputManager.cs
  Assets/GIL/Scripts/Movement/PlayerLook.cs
  Assets/GIL/Scripts/Movement/PlayerMotor.cs
  Assets/GIL/Scripts/Test/Interaction.meta
  Assets/GIL/Scripts/Test/Interaction/[Test] Interaction-KST.cs
  Assets/GIL/Scripts/Test/Interaction/[Test] Interaction-KST.cs.meta
  Assets/GIL/Scripts/Test/Status/[Test] PlayerInteraction.cs
  Assets/GIL/Scripts/Test/Status/[Test] PlayerInteraction.cs.meta
Labels: enhancement, feature

#26 [Feat] 타일 시스템 중 일부 기능 구현
  Assets/LHN/Scripts/InputManager.cs
  Assets/LHN/Scripts/InputManager.cs.meta
Labels: feature

#30 [Feat, Docs] 플레이어 움직임 프로토타입 구현 완료, 프리팹화 완료
  Assets/GIL/Prefabs.meta
  Assets/GIL/Prefabs/Export.meta
  Assets/GIL/Prefabs/Export/Player.prefab
  Assets/GIL/Prefabs/Export/Player.prefab.meta
  Assets/GIL/Scenes/[Test] PlayerMovementScene.unity
  Assets/GIL/Scripts/Movement/PlayerMotor.cs
  Assets/GIL/Scripts/Status/PlayerStatus.cs
Labels: documentation, feature

#34 [Docs] PlayerStatus에 대한 요약 README.md 파일 생성
  Assets/GIL/Prefabs/Test.meta
  Assets/GIL/Prefabs/Test/[Test] Player_Instance_Test.prefab
  Assets/GIL/Prefabs/Test/[Test] Player_Instance_Test.prefab.meta
  Assets/GIL/Prefabs/Test/[Test] RealTimeTest.prefab
  Assets/GIL/Prefabs/Test/[Test] RealTimeTest.prefab.meta
  Assets/GIL/Prefabs/Test/[Test] StatusTextCanvas.prefab
  Assets/GIL/Prefabs/Test/[Test] StatusTextCanvas.prefab.meta
  Assets/GIL/Prefabs/Test/[Test] UITester.prefab
  Assets/GIL/Prefabs/Test/[Test] UITester.prefab.meta
  Assets/GIL/Scenes/[Test] CharactorScene.unity
  Assets/GIL/Scenes/[Test] PlayerMovementScene.unity
  Assets/GIL/Scripts/Movement/PlayerInputManager.cs
  Assets/GIL/Scripts/Movement/PlayerMotor.cs
  Assets/GIL/Scripts/Status/Status_README.md
  Assets/GIL/Scripts/Status/Status_README.md.meta
  Assets/GIL/Scripts/Test/Status/[Test] StatusRealtime.cs
Labels: documentation, feature

#38 [Fix] Farm UI FIxed
  Assets/KST/Scenes/[Test]Farm.unity
  Assets/KST/Scripts/TileSys/Tile.cs
Labels: bug

#41 [Fix] 빈 슬롯 Drag & Drop 버그 수정
  Assets/SDW/Scripts/UI/Inventory/MouseItemView.cs
Labels: bug

#42 [Fix] 타일 전환 시 인터렉트 UI 딜레이 추가
  Assets/KST/Scripts/TileSys/FarmTile.cs
Labels: bug

#44 [Feat] Dissolve Shader 추가
  Assets/SDW/Scripts/Shader.meta
  Assets/SDW/Scripts/Shader/DissolveEffect.cs
  Assets/SDW/Scripts/Shader/DissolveEffect.cs.meta
  Assets/SDW/Shader.meta
  Assets/SDW/Shader/Dissolve.shadergraph
  Assets/SDW/Shader/Dissolve.shadergraph.meta
  Assets/SDW/Shader/Mat_Dissolve.mat
  Assets/SDW/Shader/Mat_Dissolve.mat.meta
  Assets/Scenes/AlphaScene.unity
Labels: feature

#50 [Feat] 1인칭 Viewmodel 구현
  Assets/GIL/Prefabs/Export/Viewmodel.prefab
  Assets/GIL/Prefabs/Export/Viewmodel.prefab.meta
  Assets/GIL/Prefabs/Test/[Test] Axe.prefab
  Assets/GIL/Prefabs/Test/[Test] Axe.prefab.meta
  Assets/GIL/Prefabs/Test/[Test] None.prefab
  Assets/GIL/Prefabs/Test/[Test] None.prefab.meta
  Assets/GIL/Prefabs/Test/[Test] Pickaxe.prefab
  Assets/GIL/Prefabs/Test/[Test] Pickaxe.prefab.meta
  Assets/GIL/Prefabs/Test/[Test] Player.prefab
  Assets/GIL/Prefabs/Test/[Test] Player.prefab.meta
  Assets/GIL/Prefabs/Test/[Test] Shovel.prefab
  Assets/GIL/Prefabs/Test/[Test] Shovel.prefab.meta
  Assets/GIL/Scenes/[Test] PlayerViewmodelScene.unity
  Assets/GIL/Scenes/[Test] PlayerViewmodelScene.unity.meta
  Assets/GIL/Scenes/[Test] ViewModelScene - Copied from Alpha.unity
  Assets/GIL/Scenes/[Test] ViewModelScene - Copied from Alpha.unity.meta
  Assets/GIL/Scripts/Viewmodel.meta
  Assets/GIL/Scripts/Viewmodel/ViewmodelManager.cs
  Assets/GIL/Scripts/Viewmodel/ViewmodelManager.cs.meta
  Assets/GIL/ViewModel_Material.mat
  Assets/GIL/ViewModel_Material.mat.meta
  ProjectSettings/TagManager.asset
Labels: feature

#52 [Feat] 개척 UI 개발
  Assets/KST/Scenes/[Test]AlphaScene.unity
  Assets/KST/Scenes/[Test]AlphaScene.unity.meta
  Assets/KST/Scenes/[Test]Exploit Scene.unity
  Assets/KST/Scenes/[Test]Exploit Scene.unity.meta
  Assets/KST/Scripts/UI/ExploitUI.cs
  Assets/KST/Scripts/UI/ExploitUI.cs.meta
  Assets/KST/Scripts/UI/FarmUI.cs
Labels: feature
